dev-fix-testcontainers-NoClassDefFoundError: Adjusted TimeSeriesClient unit tests to fit updated functions in TimeSeriesClient, RDFCLient, and SPARQLCLient and removed unused Mockito mocks